
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEVMTUcPXm1yOzkrdn2Ti3P8FrqaHQlA',
    authDomain: 'campusmarket-742ab.firebaseapp.com',
    projectId: 'campusmarket-742ab',
    storageBucket: 'campusmarket-742ab.firebasestorage.app',
    messagingSenderId: '712569186688',
    appId: '1:712569186688:web:c8acfe48b663d9fda87965'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1Wmu0BhUctdjoNI-UV3MH04FpE0c7SM',
    appId: '1:712569186688:android:019457152132c480a87965',
    messagingSenderId: '712569186688',
    projectId: 'campusmarket-742ab',
    storageBucket: 'campusmarket-742ab.firebasestorage.app'
  );
}
